name: first pipeshellpipeline
on: push

jobs: 
  firstpipeline:
    runs-on: ubuntu-latest
    steps:
      - name: run shell commands
      - run: | 
          mymessage="test"
          echo '${mymessage}'          
          echo ${mymessage}


