name: first pipeshellpipeline
on: push

jobs: 
  firstpipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: run shell commands
        run: | 
          mymessage="test"
          echo '${mymessage}'          
          echo ${mymessage}
          mymessage=$(<README.md)
          echo ${mymessage}
          cat README.md


